print("Bijna 17 jaar geleden, hier niet zo ver vandaan,")
print("werd en jongetje geboren, boven een stinkende viskraam.")
print("Het geschreeuw van de Ten Katemarkt was zeker niet gering.")
print("Maar het wist niet het gehuil te dempen van de jonge zuigeling")
print("Het zachte zonlight scheen door het zolderraam naar binnen,")
print("en de ouders van het jongetje probeerde een naam te verzinnen.")
print("Ze vonden dat Abraham een naam was die goed bij hem past,")
print("dat was de naam van zijn opa die een joodse verzetsstrijder was.")
print("Hij heet dus eigenlijk Abraham maar zijn roepnaam dat is Bram,")
print("en het duurde niet lang tot creativiteit zijn leven binnen kwam.")
print("Bram’s ouders waren allebei acteur en actrice,")
print("dus tussen muziek, tekenen, en acteren kon hij slecht kiezen.")
print("Hij besloot om niet te kiezen tussen een van deze paden,")
print("maar hij besloot dat zijn passie lag bij dingen maken.")
print("Muziek, games, tekeningen noem het maar op,")
print("zolang hij iets nieuws maakt vindt hij het top.")
print("Uiteindelijk kwam de tijd om te moeten kiezen.")
print("het was moeilijk maar hij besloot om zich in games te gaan verdiepen.")
print("Nu zit hij op het Media College leert hij nieuwe dingen kennen,")
print("dus hij bereidt zich voor om de Python te kunnen temmen.")
